import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/commons/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-[1440px] mx-auto my-0  h-screen pb-[45] sm:flex">
          <Nav className="w-full flex justify-between items-center  px-8 py-4 bg-gray-800  rounded-b-lg  sm:flex-col sm:w-[50px] sm:justify-start sm:gap-10" />
          <div className="w-full">{children}</div>
        </main>
        <div id="modal" className=""></div>
      </body>
    </html>
  );
}
